Added a way to clear the date in the sidebar
PermanentOrg/web-app pull request #220
Opened 2023-05-02 10:52 UTC by crisnicandrei

I have added a new button beneath each date picker (file or folder) and when the user clicks on it the date gets updated through an update request to the backend with a null value

It works but when I refresh the previous date is set back again, maybe the date is protected again just like the archive type was?

2023-05-02 10:58 UTC, crisnicandrei commented
@cecilia-donnelly @meisekimiu This works in the front-end but when i refresh the page the previous date is back again. 

Maybe the safeguard is set also for dates? I did a bit of digging and this is what I found, what do you think?
<img width="366" alt="Screenshot 2023-05-02 at 13 58 11" src="https://user-images.githubusercontent.com/62384997/235648567-c9afedd5-66e0-4791-8065-f56dce6b532e.png">

2023-05-02 14:52 UTC, cecilia-donnelly commented
@crisnicandrei We do set a lot of dates, so it's confusing, but those are system-generated dates that are on the protected list. The display date is editable.

2023-05-03 08:17 UTC, crisnicandrei commented
@cecilia-donnelly when i send displayDT as null the response comes back with the created date i think? 

I have made a screen recording of the behaviour 

https://user-images.githubusercontent.com/62384997/235864401-ab3fc1ea-1456-4077-9481-1a05da97f735.mov

2023-05-03 19:31 UTC, cecilia-donnelly commented
This is working fine for me locally on an image, and I do think records are more important than folders here, so my recommendation would be to limit this to records in this PR.

Personally I think it would be better to have the "clear" option inside the datepicker. Can you do your usual round of feedback in slack (via screenshot or screen recording) for how this looks?

2023-05-04 07:04 UTC, crisnicandrei commented
@cecilia-donnelly I can of course :D, but can you please test it on a video? It works for images too for me but not for videos

2023-05-08 15:11 UTC, cecilia-donnelly requested changes
Thanks for working on this! Just on the code level:

1. Can you clean up the git history? We don't like to have merge commits - you can rebase on main to get rid of those. This is small enough that it can probably all be one commit.
2. You shouldn't have changes to package-lock.json since you didn't change package.json -- might be related to https://github.com/npm/cli/issues/3225 ? What version of npm are you on?

2023-05-09 09:55 UTC, crisnicandrei commented on src/app/shared/components/inline-value-edit/inline-value-edit.component.ts
> +    console.log(this.item)
I have removed the console log

2023-05-09 09:57 UTC, crisnicandrei commented
@cecilia-donnelly I am running npm 8.19.2. The reason i had to run npm install was because of the angular update( I think) because I was getting various errors from some imports. Is there a way to revert that? I think it is related to that bug

2023-05-09 10:09 UTC, crisnicandrei commented
@cecilia-donnelly should i squash all the commits when merging? with squash and merge?

2023-05-09 16:15 UTC, cecilia-donnelly commented
I would squash the commits now so you have control over the commit message rather than using the GitHub squash-and-merge.

As for the package-lock changes, it makes perfect sense that you had to `npm install`. I'm thinking that maybe if you revert the package-lock changes and rebase on main then you should be able to run the app and not have changes in that file. I'm happy to pair on that after standup tomorrow if you haven't done much git commit management before.

2023-05-10 11:21 UTC, crisnicandrei commented
@cecilia-donnelly I have squashed the commits and removed package-lock!

2023-05-10 21:33 UTC, cecilia-donnelly commented
Thanks @crisnicandrei ! So I think this is waiting for backend changes now, right? Can you list which filetypes you know to be broken at the moment? Is it just videos and folders?

2023-05-11 07:02 UTC, crisnicandrei commented
@cecilia-donnelly interestingly enough, I thought all video files might be causing issues, but yesterday while testing something else I have noticed that I could clear the date on .wmv files but not on .mov files. Does this help with this further? :)

2023-07-18 20:21 UTC, cecilia-donnelly commented
Removing my review request since this is waiting on back-end changes. We'll restart work on this once those are complete.

2024-08-05 16:11 UTC, closed without merging