Per 9268/public archive links not working
PermanentOrg/web-app pull request #231
Opened 2023-05-19 14:06 UTC by crisnicandrei

2023-05-24 04:03 UTC, cecilia-donnelly requested changes
I didn't include "https://" at the beginning of my entries, so they opened as subdirectories of my local copy - e.g. https://ng.permanent.org:4200/linkedin.com/testname. I think this should be able to handle `linkedin.com/testname` in the input field and open correctly at https://linkedin.com/testname (of course that'll 404, but that's correct).

2023-05-24 04:04 UTC, cecilia-donnelly commented
Similarly, the email should open as a `mailto` link.

2023-05-24 16:16 UTC, meisekimiu requested changes
Public profiles can support multiple instances of these various fields. A user can add *multiple* email addresses or URLs to their profile. I'm realizing now that the current implementation only shows one of these per category. Let's change this so it iterates through all URLs on their profile to display them all.

I think the Facebook functionality can be improved a bit too (right now if any URL has "facebook" in it at all, it will add a Facebook icon to it, even if you were linking to a URL like https://twitter.com/facebook which is obviously not a Facebook URL!). However I think the experience team is going to discuss what we want to do with that functionality soon so it might be best to leave that work for a separate ticket.

(Also +1 @cecilia-donnelly's request to use a "mailto:" link for email addresses.)

2023-05-24 16:29 UTC, cecilia-donnelly commented on src/app/public/components/public-archive-web-links/public-archive-web-links.component.ts
> +        url = 'http://' + url;
I use neverssl.com for this if you're looking for one in the future

2023-05-24 17:13 UTC, crisnicandrei commented on src/app/public/components/public-archive-web-links/public-archive-web-links.component.html
> +    <div (click)="navigate(website)" *ngIf="website" class="link-container">
@meisekimiu but shouldn't the icons be clickable as well? If not, then yes i could replace the tags. @cecilia-donnelly what do you think?

2023-05-24 17:19 UTC, crisnicandrei commented
@cecilia-donnelly @meisekimiu should i use for now only the icon of the email addresses and map through all the values? Or should I wait for the experience team to discuss it?

2023-05-26 17:15 UTC, cecilia-donnelly commented
@crisnicandrei just talked to @k8lyn6 and she said she'd prefer no custom icons for now (no facebook, no email, nothing). Thanks!

2023-06-05 21:24 UTC, cecilia-donnelly requested changes
Some very small tweaks, but I think this is ready for QA.

2023-06-05 21:24 UTC, cecilia-donnelly commented on src/app/public/components/public-archive-web-links/public-archive-web-links.component.ts
> +    window.open(url, '_blank');
Technically you're [not supposed to open links in a new tab](https://www.w3.org/TR/WCAG20-TECHS/G200.html) by default. I don't know if we have a standard practice for this in the codebase so far, but I know our users generally want the back button to work. Do you know what we do elsewhere, @meisekimiu ? If there isn't a clear pattern, let's open these in the same tab.

2023-06-05 21:24 UTC, cecilia-donnelly commented on src/app/public/components/public-archive-web-links/public-archive-web-links.component.ts
> +    }
Let's get rid of this special Facebook code.

2023-06-05 21:24 UTC, cecilia-donnelly commented on src/app/shared/pipes/prepend-protocol.pipe.ts
> +    return value
Missing semicolon, which probably means you need to run prettier on this file.

2023-06-15 17:53 UTC, cecilia-donnelly requested changes
This currently doesn't load (at least for me), so needs to be rebased on main. Sorry about that! If you don't see the same problem let me know.

2023-06-23 13:39 UTC, k8lyn6 requested changes
This is looking good! One small thing -- it looks like the websites only show up if there is also an email address filled out. Steps to replicate:

- in a new archive without profile information, fill out at least one website in the profile
- check and observe that the website does not show up in the profile
- go back and add an email address
- check the public profile and observe that the website now shows up

2023-06-23 13:48 UTC, crisnicandrei commented
@k8lyn6 i have fixed the issue you have found!

2023-06-23 15:09 UTC, k8lyn6 approved these changes
Looks good!

2023-06-26 18:49 UTC, cecilia-donnelly commented on src/app/public/components/public-archive-web-links/public-archive-web-links.component.html
> +    <div (click)="navigate(website)" *ngIf="website" class="link-container">
Since we opted to get rid of the icons it looks like these are now `<a>` tags, as requested.

2023-06-26 18:59 UTC, cecilia-donnelly approved these changes
Looks good! Thanks for including tests.

2023-06-26 19:01 UTC, crisnicandrei commented
@meisekimiu can you please take a look too?

2023-06-27 20:18 UTC, meisekimiu approved these changes

2023-06-27 20:23 UTC, merged