PER-9267: use show more for long descriptions
PermanentOrg/web-app pull request #236
Opened 2023-05-24 12:10 UTC by crisnicandrei

For this functionality, I thought that 100 characters for the short text might be enough, but that could change upon request.

When the user clicks the new span with show more, the full text gets displayed, and when the user clicks on see less, the shortened version is being shown.

The short text is a new variable saved inside the component

2023-05-30 14:54 UTC, meisekimiu reviewed
This looks good, although I had to rebase my copy of this branch onto main so that #234 took effect as well. I've added @k8lyn6 onto this PR for QA approval. Can you rebase this onto main so we can deploy it to dev with the previous fixes included as well?

2023-05-30 19:34 UTC, k8lyn6 requested changes
Overall, the read more looks good! One major thing: when the "Tell Us About This [archive type]" description that we've implemented the read more on is blank, it currently removes all sections of the public profile (i.e. if there's no description, the public profile shows up as blank even if other sections are filled out). We need to fix this bug before we deploy this change. I think if the "Tell Us About This..." section is blank, there shouldn't be a "read more" or anything.


Another minor thing:
- Ideally, if a description is less than the cutoff length for the read more, the read more shouldn't show up. This could be confusing for members who think they'll get more text when really, that's all there is. (For instance, if the description reads "A short description", there shouldn't be a read more after that because it's short enough to fit.)

2023-06-23 15:35 UTC, k8lyn6 approved these changes
Comments were addressed. Looks good!

2023-06-23 15:39 UTC, meisekimiu approved these changes

2023-06-23 15:42 UTC, merged