WIP Per 9237 gift storage interface
PermanentOrg/web-app pull request #248
Opened 2023-06-13 08:23 UTC by crisnicandrei

This pr's purpose is the implementation of the gift storage interface.

I have added a new tab to the dropdown for the gift component. I have created a new component which in which the new form lies where the user must input the email, amount and the message. Upon confirmation a new modal pops up for confirmation.

The api is not yet implemented, so this is only the interface

2023-07-24 19:18 UTC, meisekimiu commented
Can you rebase this on main and fix the conflicts?

2023-07-25 17:52 UTC, cecilia-donnelly requested changes
This may have been preexisting, but I can now reach https://ng.permanent.org:4200/app/(private//dialog:storage/done) and see an empty screen in the modal. I think we always want something to appear in the modal, likely the "add storage" page by default.

More concerning, I tried gifting 1.2 GB of storage, which is not allowed since we are limiting to whole numbers of gigabytes. I got a 500 error back from the server with the message `SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "-1288490188.8"CONTEXT:  unnamed portal parameter $1 = '...'`. but the user-facing message was "Success!" We should also remove the decimal point from the placeholder text and have it just read "0" or similar to make it clear that users need to send only whole numbers of gbs as gifts. [Here is the slack conversation where Robert suggested sticking to whole gbs for gifting](https://permanent-org.slack.com/archives/C01ARGVA849/p1684350429130289). Mind you, the server error should have been a validation issue, not a sql error, so I'm also looking into that.

2023-07-25 20:03 UTC, crisnicandrei commented
@cecilia-donnelly I have pushed some changes, could you please recheck? thanks

2023-07-28 14:48 UTC, cecilia-donnelly requested changes
Thanks for validating the storage amount is a whole number! However, just disabling the button is very confusing. Can you add a red box around the problematic entry or something like that? (cc @k8lyn6 since this is really a design question - is there language you'd like to use for the error if a person tries to give 1.5 GB and we're only allowing them to gift integer gbs of storage?)

2023-07-28 15:34 UTC, k8lyn6 commented
@cecilia-donnelly How about: "Storage can only be gifted in 1GB increments."

2023-07-28 17:15 UTC, crisnicandrei commented
@cecilia-donnelly @k8lyn6 should there be a message for invalid email addresses as well?

2023-07-31 17:40 UTC, k8lyn6 commented
@cecilia-donnelly users can gift storage to people who aren't Permanent members, correct? I don't think we normally have a message for invalid email addresses, so I don't think we need one here.

2023-07-31 21:18 UTC, crisnicandrei commented
@k8lyn6 i have added a message if the string is not a valid message (e.g andrei instead of andrei@domain.com)

2023-10-04 17:24 UTC, crisnicandrei commented
@k8lyn6 @cecilia-donnelly @meisekimiu I have tested this with the backend changes, and it looks good so I would say it can be reviewed

2023-10-10 21:29 UTC, cecilia-donnelly reviewed
A couple things I noticed when trying this out:
1. Storage doesn't update immediately - but I see that's fixed in https://github.com/PermanentOrg/web-app/pull/308, so we'll just have to keep an eye on any conflicts when we merge!
2. If I try to give away more storage than I have, the "Send Gift Storage" button grays out but there's no message. I think it would be helpful to include a message there to alert people to what's going on.

2023-10-10 21:49 UTC, crisnicandrei commented
@cecilia-donnelly where do you check to see if the storage was not updated? I am asking just so I know where I should look. In the dialog or the account dropdown?

2023-10-10 21:50 UTC, cecilia-donnelly commented
@crisnicandrei I checked both.

2023-10-11 07:18 UTC, crisnicandrei commented
@cecilia-donnelly it updates for me!
https://github.com/PermanentOrg/web-app/assets/62384997/ef40c82a-03c4-4661-ad13-105853d8584f

2023-10-16 21:20 UTC, cecilia-donnelly reviewed
Some requests, but overall this looks good to me @crisnicandrei! I defer to @meisekimiu on actual code organization as usual.

2023-10-16 21:20 UTC, cecilia-donnelly commented on src/app/core/components/confirm-gift-dialog/confirm-gift-dialog.component.spec.ts
> +      email: 'test@email.com',
I usually use "example.com" for things like this, so I don't accidentally use a real email address (even though this won't send any emails). You'll see that in several other places in this codebase, too, so it's good for consistency.

2023-10-16 21:20 UTC, cecilia-donnelly commented on src/app/core/components/gift-storage/gift-storage.component.spec.ts
> +  it('the button is disabled if the email is not valid', async () => {
Nitpicky, but it seems like the convention for test names is to use a more active sentence, like "disables the button if the email is not valid."

2023-10-16 21:20 UTC, cecilia-donnelly commented on src/app/core/components/gift-storage/gift-storage.component.spec.ts
> +  });
Maybe add a test of trying to give more storage than the member has available?

2023-10-16 21:20 UTC, cecilia-donnelly commented on src/app/core/components/storage-dialog/storage-dialog.component.ts
>  import { ActivatedRoute, ParamMap } from '@angular/router';
It seems like you ran prettier on this file - can you add the pragma at the top so it's automatically checked going forward?

2023-10-19 15:18 UTC, meisekimiu commented on src/app/core/components/confirm-gift-dialog/confirm-gift-dialog.component.ts
> +      this.giftResult.next(false);
These lines are not covered by tests. We should probably write some tests that cover what happens if the giftStorage call goes wrong.

2023-10-19 15:21 UTC, meisekimiu commented on src/app/core/components/gift-storage/gift-storage.component.ts
> +      }
This whole function that runs when the Gifting Result is successful is also not covered by tests.  Do we want to test this bit of functionality?

2023-10-24 20:46 UTC, k8lyn6 requested changes
Looking good! I already mentioned some things in [this thread on Slack](https://permanent-org.slack.com/archives/C01ARGVA849/p1698164549123139), but a few minor front end things not included in that thread:
- the text says "they must log in to/create an account in order to claim their storage." Can you remove the "/" and add a space between "to" and "create"?
- once you've finished the gifting flow and return to the gifting screen, I think the fields should go back to being blank instead of filled in with the previous info, if possible

2023-10-25 12:36 UTC, crisnicandrei commented
@k8lyn6 done!

2023-10-27 13:35 UTC, k8lyn6 requested changes
Sorry, one minor change! I've read that last sentence about 20 times and it's a little confusing. Can we change it to:

>Gift any amount of your unused storage to someone else. You can send storage to both current Permanent users and those who do not yet have an account. Those without an account must create an account in order to claim their storage.

Other than that, it looks great! Thanks Andrei!

2023-10-27 14:04 UTC, k8lyn6 approved these changes

2023-10-29 18:45 UTC, merged