Per 9296 using arrow keys to move cursor
PermanentOrg/web-app pull request #255
Opened 2023-06-23 11:34 UTC by crisnicandrei

I have created a new service which will save the current state of the input (if it is editing or not) and then disable or enable the swiping accordingly

2023-06-27 20:57 UTC, meisekimiu requested changes
Instead of creating a brand new service for this functionality, I think we can just have the `inline-value-edit` component stop further propagation of the `KeyboardEvent` to the rest of the page (where it gets picked up by the `file-viewer-component`).

I made a proof of concept of this by adding the following lines to `inline-value-edit.component.ts` at the end of the `ngOnInit()` method (specifically I edited it on a version of `main` rather than this specific branch):
```ts
this.elementRef.nativeElement.addEventListener(
  'keydown',
  (event: KeyboardEvent) => {
    event.stopPropagation();
  }
);
```

What do you think of this solution as an alternative? I think ideally the file-viewer shouldn't have to know whether or not any input fields are being edited, instead it should be oblivious to any keyboard input at all. Do you see any pros/cons between the two methods?

2023-06-28 10:12 UTC, crisnicandrei commented
@meisekimiu I think your method is better than mine. It makes more sense to handle it inside the component instead of having a service to do it, because if we have the same problems in the future we would have to use the service again and again.

With your method everything is taken care of inside the component, so I will update the code to use that. Thanks!

2023-06-28 10:29 UTC, crisnicandrei commented
@meisekimiu thanks for your suggestion! I have updated the code

2023-06-30 15:17 UTC, k8lyn6 approved these changes
This looks good to me!

2023-06-30 15:19 UTC, merged