PER-9438-search-results-in-subfolders
PermanentOrg/web-app pull request #346
Opened 2024-01-11 14:17 UTC by crisnicandrei

Added the archive number of the parent folder and the link id when navigating in the search results into a nested record, thus forcing the data service to change the current folder.

Steps to test: 
1. Publish a folder with any record inside of it.
2. Go to the public archive and search for the nested record
3. It should open the record in the file viewer.

2024-01-16 16:49 UTC, meisekimiu approved these changes

2024-03-04 19:52 UTC, emlesienk requested changes
The search wasn't working on dev when I tried. Branch is out of date so you might need to update for the new code to fix this issue.

2024-03-05 17:46 UTC, crisnicandrei commented
@emlesienk did this work?

2024-03-05 18:15 UTC, emlesienk commented
> @emlesienk did this work?

Yes, thank you.

2024-03-05 19:14 UTC, merged