Per 9422 mobile banner
PermanentOrg/web-app pull request #348
Opened 2024-01-18 13:58 UTC by crisnicandrei

@meisekimiu could you please take a look at the logic from the new banner component when trying to use the deep link? I have tried to redirect the user to the stores if the deep links do not work, but I could not get it working. Do you have any ideas?

2024-01-18 16:27 UTC, meisekimiu commented
I don't think we should be redirecting users manually if the deep link doesn't work, since that would just make the entire web app completely unusable on mobile.

2024-01-18 17:13 UTC, crisnicandrei commented
@meisekimiu do you have any suggestions? Should we look for a library that could handle this?

2024-01-18 17:18 UTC, crisnicandrei commented
@meisekimiu https://github.com/ain/smartbanner.js

2024-01-29 15:12 UTC, meisekimiu reviewed
I think the `pr-banner` component should be renamed to something a bit more descriptive, such as `pr-mobile-banner`, since "banner" is a bit too vague on its own.

2024-01-29 15:12 UTC, meisekimiu commented on src/app/shared/services/banner/banner.service.spec.ts
> +/* @format */
```suggestion
/* @format */
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
```

2024-01-29 15:12 UTC, meisekimiu commented on src/app/shared/services/banner/banner.service.ts
> +    'https://play.google.com/store/apps/details?id=org.permanent.PermanentArchive' as const;
Why the `as const` here? Could we use `private readonly` instead?

2024-01-30 19:15 UTC, meisekimiu approved these changes

2024-02-13 20:12 UTC, k8lyn6 requested changes
This is looking really good! A few things (cc @yeslikesolo):

- On Safari on iOS, when you tap Go to App, it pops open a dialog from Safari saying that the address is invalid. Is there anything you can do to fix that for Safari? See photo.
![IMG_2070](https://github.com/PermanentOrg/web-app/assets/16201121/6cea251f-0311-445d-9009-c57d39d71507)
- If you do have the app installed on iOS and tap Go to App, it takes you to the app store rather than the app. Is there a way to actually redirect them to the app itself rather than the app store? Is that a dev vs prod issue? It's ok if we can't redirect to the app itself -- the app store is fine.
- Some text changes: For the headline, can we say "Unlock more with our app." And then for the text, can it say "Experience full functionality – download our app to enjoy all features seamlessly."

2024-02-13 20:20 UTC, crisnicandrei commented
@k8lyn6 for the app to redirect to the app instead of the store we would need to first merge this pr so the mobile team to be able to make their changes! That "invalid page" message on safari is because the web app is trying to open the installed app, but i can try to make it disappear somehow

2024-02-13 20:23 UTC, k8lyn6 commented
@crisnicandrei gotcha! Thanks for looking into the safari issue. I think it's okay if you aren't able to make that change.

cc @yeslikesolo

2024-02-14 15:33 UTC, k8lyn6 requested changes
Small wording change: can we change the description to say "download the Permanent app to enjoy all features seamlessly"?

And a minor spacing thing: Are we able to increase the spacing between "Experience full functionality - download the Permanent app to enjoy all features seamlessly" and the "Go to App" button to make it equal to the others? It looks a little smaller than the spacing between the others.

I also deleted the app and still got the "invalid link" on Safari. Were you able to look into that error message?

cc @yeslikesolo

2024-02-15 15:14 UTC, k8lyn6 approved these changes
Looks awesome! Thanks so much Andrei!

2024-02-20 17:09 UTC, merged