PER-8458-profile-completion
PermanentOrg/web-app pull request #353
Opened 2024-02-05 09:04 UTC by crisnicandrei

I have removed some of the values from the profile completion checklist, because some of them were not used in the profile, preventing it to reach 100%. I have also made it easier for the profile to reach 100%, needing only 1 entry for each category.

2024-02-05 21:08 UTC, meisekimiu requested changes
Left some feedback on the tests.

Have you tested this on different archive types? (Personal vs Group vs Organization). These different types have differing metadata fields.

2024-02-05 21:08 UTC, meisekimiu commented on src/app/shared/services/profile/profile.service.spec.ts
> +  it('should return the correct completion value', async () => {
Please give each test a unique name.

2024-02-05 21:52 UTC, crisnicandrei commented
@meisekimiu I did test on different archive types

2024-02-05 22:05 UTC, crisnicandrei commented on src/app/shared/services/profile/profile.service.spec.ts
> +  it('should return the correct completion value', async () => {
@meisekimiu done

2024-02-06 15:09 UTC, meisekimiu approved these changes

2024-02-06 22:06 UTC, k8lyn6 approved these changes
I think this looks good and solves the problem of never getting to 100%. There are some further small improvements I think we could make, but I'll make separate tickets for those. Thanks Andrei!

2024-02-07 07:47 UTC, merged