Remove create archive skip link
PermanentOrg/web-app pull request #428
Opened 2024-07-23 15:23 UTC by meisekimiu

There are a few broken inconsistencies I initially missed in review for the GLAM onboarding integration pull requests:
* A "skip this step" link appears on the archive creation step of onboarding. This is not supposed  to show up here, and clicking on it does nothing because it was not programmed to have functionality when clicked on this screen.
* The "create archive for me" link is visibly greyed out until the user has selected an archive type. This should not be the case since the whole point of that link is to skip picking an archive type.

This may cause some errors to pop up on the GLAM side of the application, but I believe restoring the live onboarding experience takes priority over that.

Bugs like this are why I've been trying to advocate for us using [Branch By Abstraction](https://martinfowler.com/bliki/BranchByAbstraction.html) when it comes to big redesigns like this. If we implement future redesigns like this, the old logic will be completely untouched and so there are much lower odds of bugs like this popping up. (Though care still has to be taken in making sure new code is properly isolated! Because we didn't fully isolate the checklist, some of its functionality ended up causing the bug that was fixed in #427)

2024-07-23 16:22 UTC, crisnicandrei approved these changes

2024-07-24 16:20 UTC, cecilia-donnelly approved these changes
Thanks for catching these, @meisekimiu !

2024-07-31 16:35 UTC, yeslikesolo reviewed
- "skip this step" is still visible on archive creation screen; need to remove
- "make my archive for me" link is fixed

2024-08-02 20:03 UTC, meisekimiu commented
I believe I've fixed these issues even if the user hits back now.

2024-08-05 15:14 UTC, k8lyn6 commented
@yeslikesolo can you retest?

2024-08-07 14:23 UTC, yeslikesolo requested changes
The "skip this step" link is still showing up on Create Archive screen.

2024-08-07 14:51 UTC, meisekimiu commented
> The "skip this step" link is still showing up on Create Archive screen.

Can you send a screenshot of where/when it's appearing? At this point I can't find anything that causes it to show up.

2024-08-07 16:26 UTC, yeslikesolo commented
@meisekimiu here is a screenshot. The button is visible but has no action when clicked on.
![screenshot skip this step](https://github.com/user-attachments/assets/c3f1c414-47a2-4b42-89bb-aa69006dd8a8)

2024-08-07 18:05 UTC, meisekimiu commented
I can't get this to show up, even when I deploy it to dev. Can you test it again?

![Screenshot from 2024-08-07 13-04-24](https://github.com/user-attachments/assets/47b7ad55-0f2a-4345-8f25-294a5a26dad9)

2024-08-09 16:38 UTC, yeslikesolo commented
It's fixed! Not showing up for me anymore

2024-08-09 16:50 UTC, meisekimiu commented
@yeslikesolo can you approve this PR if you think it's good? Thanks!

2024-08-09 18:54 UTC, yeslikesolo approved these changes

2024-08-09 21:04 UTC, merged