Per 9756 update archive type onboarding screen
PermanentOrg/web-app pull request #439
Opened 2024-08-12 16:38 UTC by crisnicandrei

Design changes for the archive type select screen. 

@yeslikesolo I am missing some texts for the "Other" and "I'm not sure yet" so we keep the header text format please!

2024-08-13 14:34 UTC, meisekimiu requested changes
I've added some small bits of initial feedback before we pass it to QA.

2024-08-13 14:34 UTC, meisekimiu commented on src/app/onboarding/components/glam/archive-type-select/archive-type-select.component.scss
>    border: 1px solid rgba(255, 255, 255, 0.16);
```suggestion
  border: none;
```
I think one of the things requested in the ticket is to remove a weird orange line that appears near the component. It seems like this change gets rid of that.

2024-08-13 14:34 UTC, meisekimiu commented on src/app/onboarding/components/glam/archive-type-select-dialog/archive-type-select-dialog.component.scss
>    border-radius: 12px 12px 0px 0px;
```suggestion
  border-radius: 12px;
```
The design for this dialog actually changed at some point after it was initially implemented. It is now not flush with the bottom of the screen, so I believe we have a consistent border radius now.

2024-08-13 14:34 UTC, meisekimiu commented on src/app/onboarding/components/glam/select-archive-type-screen/select-archive-type-screen.component.ts
>      }
Codecov is pointing out that this is missing coverage. It would be nice to write a test that renders the component with the `tag` input provided.

2024-08-23 14:50 UTC, meisekimiu approved these changes

2024-08-23 14:50 UTC, meisekimiu commented on src/app/onboarding/components/glam/archive-type-select/archive-type-select.component.scss
> +/*N @format */
```suggestion
/* @format */
```
The prettier pragma got a bit messed up here.

2024-09-05 21:35 UTC, yeslikesolo requested changes
<img width="1496" alt="Screenshot 2024-09-05 at 5 16 07 PM" src="https://github.com/user-attachments/assets/cb1262e1-b3d0-4e23-bbab-749f0654e5fb">

- Please decrease the width of H1 component Create your first archive, to half its size. It should stack or be wrapped text, aligned left. 
- Increase bold for "Archive" in h1 text for create new archive component

<img width="962" alt="Screenshot 2024-09-05 at 5 33 57 PM" src="https://github.com/user-attachments/assets/f9441c83-4221-4dad-852e-ba4058283993">

- bold archive type names: Personal, An Individual, Family, etc.

2024-09-06 12:01 UTC, crisnicandrei commented
@yeslikesolo can't do much bolder, this is tthe only bold font that i have :(

2024-09-13 13:48 UTC, k8lyn6 commented
@crisnicandrei could you confirm what font you're using for onboarding? The bold/not bold has been hard to see across onboarding and I just want to check we're using the right font. If the font is correct, could you coordinate with Tibi about why it's not looking like the design? 

@yeslikesolo once Andrei has checked that, could you re-review this?

2024-09-13 13:57 UTC, crisnicandrei commented
@k8lyn6 @yeslikesolo I think I got it right this time. Can you please recheck? It was Usual, but I had to use the extra bold instead

2024-09-16 15:30 UTC, yeslikesolo approved these changes

2024-09-17 19:11 UTC, merged