List all accepted archives at end of Glam onboarding
PermanentOrg/web-app pull request #491
Opened 2024-11-19 21:14 UTC by meisekimiu

Right now the final congratulations / "finalize" screen lists a user's created archive. If a user has archive invites they can accept multiple archives during onboarding but only one is showing and it is listed as an owner regardless of the access role of the archive. Update this congrats screen to handle multiple archives and list out all their access roles correctly.

This PR involves the creation of a new `OnboardingService` which mainly acts as a place to store "registered archives" and then get that final list of archives in the end. This is a better pattern for sharing information between components with complex flows compared to the Input/Output system we're using now, but I also think that the onboarding flow has complex enough behavior to warrant some of that behavior moving into a dedicated service anyway. I didn't want this 1 point ticket to involve a complete refactoring of glam onboarding logic, so this service is pretty bare right now. As we continue to improve the onboarding flow, I hope we can continue to move things into this service.

**Steps to test:**
1. Run through the glam onboarding flow and verify that when you create an archive it still shows up properly.
2. Run through the glam onboarding flow with multiple archive invitations, preferably with access roles besides owner. Verify that at the end of the process all archives are listed with correct access roles.

2024-11-20 18:22 UTC, meisekimiu commented on src/app/onboarding/components/glam/finalize-archive-creation-screen/finalize-archive-creation-screen.component.html
> +                alt="Custom Archive Icon"
It probably isn't and it might be better to use an `aria-labeledby` attribute instead here!

2024-11-21 09:05 UTC, crisnicandrei approved these changes

2024-11-21 17:14 UTC, yeslikesolo requested changes
**Issue with testing Step 1** - I am unable to see my newly created archive on the screen. Please see image below. After I hit "next" on this screen, it shows the updated screen with my archive listed. 
![Screenshot 2024-11-21 at 12 00 17 PM](https://github.com/user-attachments/assets/71a333d2-07e2-4e55-81c4-ee0201beed90)

Step 2 Testing Comments:
- Move paragraph text "You've been invited to..." to right hand side, above archive list.
- "accept" button is not functional

https://github.com/user-attachments/assets/a387322a-d132-4ea8-80d2-4fece364faf6

2024-12-02 20:24 UTC, k8lyn6 commented
@meisekimiu is there anything you are waiting on from me or @yeslikesolo for this? Just wanted to check!

2024-12-03 17:05 UTC, meisekimiu commented
![Screenshot from 2024-12-03 10-59-36](https://github.com/user-attachments/assets/22c1d97c-cc2e-4ea9-8d81-f61a24b7a90d)
Should the text be set up like this? In the design it's on the left side of the screen so I'm not sure how the spacing should look. @yeslikesolo / @k8lyn6 
(I've also fixed the unreadable small text on this screen)

As for the accept button issue, I'm not sure that's connected to this PR and it might be a network or other strange environment issue. Can we try testing that again? It seems to work when I test on a newly reset local development environment as well as on Staging.

2024-12-03 18:44 UTC, k8lyn6 commented
Hey @meisekimiu , my apologies but I think the text on the "Welcome with archive invitations" page should go wherever it indicates in the design. If it's on the left side, then we should keep it there. cc @yeslikesolo can you test whether the accept button is still not functional for you?

2024-12-04 16:24 UTC, yeslikesolo commented
@k8lyn6 @meisekimiu hmm that's weird, maybe I'm looking at an outdated design file? Because its on the right side for me. Either way, whichever is fine! I was following the design file that I thought was the source of truth.

2024-12-04 16:32 UTC, meisekimiu commented
![Screenshot from 2024-12-04 10-30-14](https://github.com/user-attachments/assets/d35582af-91b8-4015-aa0a-447dd4fdbb7d)
This is a screenshot of the design I checked. There is text is on the right side on some other screens, but as far as I know it's on the left on this specific screen.

2024-12-04 16:33 UTC, yeslikesolo requested changes
<img width="1507" alt="Screenshot 2024-12-04 at 11 26 38 AM" src="https://github.com/user-attachments/assets/47edf998-745d-408e-b25b-f07d001f34e7">

I know @meisekimiu flagged she already fixed the small text - just wanted to note it here too!


https://github.com/user-attachments/assets/68d18eb0-49a6-459e-85ef-8635e4de8b14

Accept button worked when I first hit accept. I then hit "create new archive", decided to go back to previous screen, and now the accept button is no longer working. Please see screen recording above.

2024-12-04 21:18 UTC, yeslikesolo approved these changes
Everything is fixed, thanks @meisekimiu !

2024-12-05 14:13 UTC, merged