Add background to FamilySearch Import Modal
PermanentOrg/web-app pull request #497
Opened 2024-12-04 15:28 UTC by meisekimiu

Add a background to the FamilySearch Import Modal, since it only had a transparent background. This was a style breakage caused by our migration to thew new CDK dialog.

Ideally this would be testable in Storybook but these components were not designed to be mocked very easily and efforts to put them in a Storybook story only ended in strange errors.

**Steps To Test:**
1. Go to apps and connect to FamilySearch
2. Import a family tree
3. Verify that all modals, in all steps of the process, have a background

2024-12-04 20:08 UTC, liam-lloyd approved these changes

2024-12-04 22:01 UTC, yeslikesolo reviewed
I've tried connecting a familysearch account and keep running into this screen. I've tried making new permanent accounts on dev and link the new account, but each time I end up at this same screen. 

![image](https://github.com/user-attachments/assets/333e186b-316c-4618-b79f-729981b1067c)

2024-12-04 23:00 UTC, k8lyn6 requested changes
Hey @meisekimiu it looks like the modal doesn't scroll and goes off the page right now, at least on Chrome. I'm not able to see the full list, and there's no "submit" button or anything. See screenshot. I'd love for this to go out in tomorrow's deployment if we're able to do it, but it's okay if not!
![Screenshot 2024-12-04 at 5 58 13 PM](https://github.com/user-attachments/assets/853259f6-a52f-490e-925c-e57796ac9669)

@yeslikesolo once Natalie has made changes, can you take over QA for this? You have to deploy to staging because we can't test FamilySearch on dev. To deploy to staging, you build the branch just like you would on dev, just in the "Staging Build" tab. Then you'll have to manually deploy it yourself on the infrastructure page. Ping me if you have questions about it!

2024-12-05 15:14 UTC, meisekimiu commented
![Screenshot from 2024-12-05 09-12-45](https://github.com/user-attachments/assets/575d3e5c-e45c-4c4a-8b52-cd8be0ed74bb)
I added a scrollbar to the middle of the modal so that the "Select Person(s) To Import" text and the buttons are always visible even if there's a long list of members.

2024-12-05 17:28 UTC, yeslikesolo requested changes
Changes approved! Sorry I clicked the wrong button >.<

2024-12-05 17:35 UTC, yeslikesolo approved these changes

2024-12-05 17:48 UTC, merged